/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_webkit_CookieManager */

#ifndef _Included_android_webkit_CookieManager
#define _Included_android_webkit_CookieManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_webkit_CookieManager
 * Method:    native_setCookie
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_webkit_CookieManager_native_1setCookie
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     android_webkit_CookieManager
 * Method:    native_removeAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_webkit_CookieManager_native_1removeAll
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
