/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_webkit_WebView */

#ifndef _Included_android_webkit_WebView
#define _Included_android_webkit_WebView
#ifdef __cplusplus
extern "C" {
#endif
#undef android_webkit_WebView_NO_ID
#define android_webkit_WebView_NO_ID -1L
#undef android_webkit_WebView_NOT_FOCUSABLE
#define android_webkit_WebView_NOT_FOCUSABLE 0L
#undef android_webkit_WebView_FOCUSABLE
#define android_webkit_WebView_FOCUSABLE 1L
#undef android_webkit_WebView_FOCUSABLE_MASK
#define android_webkit_WebView_FOCUSABLE_MASK 1L
#undef android_webkit_WebView_FITS_SYSTEM_WINDOWS
#define android_webkit_WebView_FITS_SYSTEM_WINDOWS 2L
#undef android_webkit_WebView_VISIBLE
#define android_webkit_WebView_VISIBLE 0L
#undef android_webkit_WebView_INVISIBLE
#define android_webkit_WebView_INVISIBLE 4L
#undef android_webkit_WebView_GONE
#define android_webkit_WebView_GONE 8L
#undef android_webkit_WebView_VISIBILITY_MASK
#define android_webkit_WebView_VISIBILITY_MASK 12L
#undef android_webkit_WebView_ENABLED
#define android_webkit_WebView_ENABLED 0L
#undef android_webkit_WebView_DISABLED
#define android_webkit_WebView_DISABLED 32L
#undef android_webkit_WebView_ENABLED_MASK
#define android_webkit_WebView_ENABLED_MASK 32L
#undef android_webkit_WebView_WILL_NOT_DRAW
#define android_webkit_WebView_WILL_NOT_DRAW 128L
#undef android_webkit_WebView_DRAW_MASK
#define android_webkit_WebView_DRAW_MASK 128L
#undef android_webkit_WebView_SCROLLBARS_NONE
#define android_webkit_WebView_SCROLLBARS_NONE 0L
#undef android_webkit_WebView_SCROLLBARS_HORIZONTAL
#define android_webkit_WebView_SCROLLBARS_HORIZONTAL 256L
#undef android_webkit_WebView_SCROLLBARS_VERTICAL
#define android_webkit_WebView_SCROLLBARS_VERTICAL 512L
#undef android_webkit_WebView_SCROLLBARS_MASK
#define android_webkit_WebView_SCROLLBARS_MASK 768L
#undef android_webkit_WebView_FILTER_TOUCHES_WHEN_OBSCURED
#define android_webkit_WebView_FILTER_TOUCHES_WHEN_OBSCURED 1024L
#undef android_webkit_WebView_OPTIONAL_FITS_SYSTEM_WINDOWS
#define android_webkit_WebView_OPTIONAL_FITS_SYSTEM_WINDOWS 2048L
#undef android_webkit_WebView_FADING_EDGE_NONE
#define android_webkit_WebView_FADING_EDGE_NONE 0L
#undef android_webkit_WebView_FADING_EDGE_HORIZONTAL
#define android_webkit_WebView_FADING_EDGE_HORIZONTAL 4096L
#undef android_webkit_WebView_FADING_EDGE_VERTICAL
#define android_webkit_WebView_FADING_EDGE_VERTICAL 8192L
#undef android_webkit_WebView_FADING_EDGE_MASK
#define android_webkit_WebView_FADING_EDGE_MASK 12288L
#undef android_webkit_WebView_CLICKABLE
#define android_webkit_WebView_CLICKABLE 16384L
#undef android_webkit_WebView_DRAWING_CACHE_ENABLED
#define android_webkit_WebView_DRAWING_CACHE_ENABLED 32768L
#undef android_webkit_WebView_SAVE_DISABLED
#define android_webkit_WebView_SAVE_DISABLED 65536L
#undef android_webkit_WebView_SAVE_DISABLED_MASK
#define android_webkit_WebView_SAVE_DISABLED_MASK 65536L
#undef android_webkit_WebView_WILL_NOT_CACHE_DRAWING
#define android_webkit_WebView_WILL_NOT_CACHE_DRAWING 131072L
#undef android_webkit_WebView_FOCUSABLE_IN_TOUCH_MODE
#define android_webkit_WebView_FOCUSABLE_IN_TOUCH_MODE 262144L
#undef android_webkit_WebView_DRAWING_CACHE_QUALITY_LOW
#define android_webkit_WebView_DRAWING_CACHE_QUALITY_LOW 524288L
#undef android_webkit_WebView_DRAWING_CACHE_QUALITY_HIGH
#define android_webkit_WebView_DRAWING_CACHE_QUALITY_HIGH 1048576L
#undef android_webkit_WebView_DRAWING_CACHE_QUALITY_AUTO
#define android_webkit_WebView_DRAWING_CACHE_QUALITY_AUTO 0L
#undef android_webkit_WebView_DRAWING_CACHE_QUALITY_MASK
#define android_webkit_WebView_DRAWING_CACHE_QUALITY_MASK 1572864L
#undef android_webkit_WebView_LONG_CLICKABLE
#define android_webkit_WebView_LONG_CLICKABLE 2097152L
#undef android_webkit_WebView_DUPLICATE_PARENT_STATE
#define android_webkit_WebView_DUPLICATE_PARENT_STATE 4194304L
#undef android_webkit_WebView_SCROLLBARS_INSIDE_OVERLAY
#define android_webkit_WebView_SCROLLBARS_INSIDE_OVERLAY 0L
#undef android_webkit_WebView_SCROLLBARS_INSIDE_INSET
#define android_webkit_WebView_SCROLLBARS_INSIDE_INSET 16777216L
#undef android_webkit_WebView_SCROLLBARS_OUTSIDE_OVERLAY
#define android_webkit_WebView_SCROLLBARS_OUTSIDE_OVERLAY 33554432L
#undef android_webkit_WebView_SCROLLBARS_OUTSIDE_INSET
#define android_webkit_WebView_SCROLLBARS_OUTSIDE_INSET 50331648L
#undef android_webkit_WebView_SCROLLBARS_INSET_MASK
#define android_webkit_WebView_SCROLLBARS_INSET_MASK 16777216L
#undef android_webkit_WebView_SCROLLBARS_OUTSIDE_MASK
#define android_webkit_WebView_SCROLLBARS_OUTSIDE_MASK 33554432L
#undef android_webkit_WebView_SCROLLBARS_STYLE_MASK
#define android_webkit_WebView_SCROLLBARS_STYLE_MASK 50331648L
#undef android_webkit_WebView_KEEP_SCREEN_ON
#define android_webkit_WebView_KEEP_SCREEN_ON 67108864L
#undef android_webkit_WebView_SOUND_EFFECTS_ENABLED
#define android_webkit_WebView_SOUND_EFFECTS_ENABLED 134217728L
#undef android_webkit_WebView_HAPTIC_FEEDBACK_ENABLED
#define android_webkit_WebView_HAPTIC_FEEDBACK_ENABLED 268435456L
#undef android_webkit_WebView_PARENT_SAVE_DISABLED
#define android_webkit_WebView_PARENT_SAVE_DISABLED 536870912L
#undef android_webkit_WebView_PARENT_SAVE_DISABLED_MASK
#define android_webkit_WebView_PARENT_SAVE_DISABLED_MASK 536870912L
#undef android_webkit_WebView_FOCUSABLES_ALL
#define android_webkit_WebView_FOCUSABLES_ALL 0L
#undef android_webkit_WebView_FOCUSABLES_TOUCH_MODE
#define android_webkit_WebView_FOCUSABLES_TOUCH_MODE 1L
#undef android_webkit_WebView_FOCUS_BACKWARD
#define android_webkit_WebView_FOCUS_BACKWARD 1L
#undef android_webkit_WebView_FOCUS_FORWARD
#define android_webkit_WebView_FOCUS_FORWARD 2L
#undef android_webkit_WebView_FOCUS_LEFT
#define android_webkit_WebView_FOCUS_LEFT 17L
#undef android_webkit_WebView_FOCUS_UP
#define android_webkit_WebView_FOCUS_UP 33L
#undef android_webkit_WebView_FOCUS_RIGHT
#define android_webkit_WebView_FOCUS_RIGHT 66L
#undef android_webkit_WebView_FOCUS_DOWN
#define android_webkit_WebView_FOCUS_DOWN 130L
#undef android_webkit_WebView_MEASURED_SIZE_MASK
#define android_webkit_WebView_MEASURED_SIZE_MASK 16777215L
#undef android_webkit_WebView_MEASURED_STATE_MASK
#define android_webkit_WebView_MEASURED_STATE_MASK -16777216L
#undef android_webkit_WebView_MEASURED_HEIGHT_STATE_SHIFT
#define android_webkit_WebView_MEASURED_HEIGHT_STATE_SHIFT 16L
#undef android_webkit_WebView_MEASURED_STATE_TOO_SMALL
#define android_webkit_WebView_MEASURED_STATE_TOO_SMALL 16777216L
#undef android_webkit_WebView_PFLAG2_DRAG_CAN_ACCEPT
#define android_webkit_WebView_PFLAG2_DRAG_CAN_ACCEPT 1L
#undef android_webkit_WebView_PFLAG2_DRAG_HOVERED
#define android_webkit_WebView_PFLAG2_DRAG_HOVERED 2L
#undef android_webkit_WebView_LAYOUT_DIRECTION_LTR
#define android_webkit_WebView_LAYOUT_DIRECTION_LTR 0L
#undef android_webkit_WebView_LAYOUT_DIRECTION_RTL
#define android_webkit_WebView_LAYOUT_DIRECTION_RTL 1L
#undef android_webkit_WebView_LAYOUT_DIRECTION_INHERIT
#define android_webkit_WebView_LAYOUT_DIRECTION_INHERIT 2L
#undef android_webkit_WebView_LAYOUT_DIRECTION_LOCALE
#define android_webkit_WebView_LAYOUT_DIRECTION_LOCALE 3L
#undef android_webkit_WebView_PFLAG2_LAYOUT_DIRECTION_MASK_SHIFT
#define android_webkit_WebView_PFLAG2_LAYOUT_DIRECTION_MASK_SHIFT 2L
#undef android_webkit_WebView_PFLAG2_LAYOUT_DIRECTION_MASK
#define android_webkit_WebView_PFLAG2_LAYOUT_DIRECTION_MASK 12L
#undef android_webkit_WebView_PFLAG2_LAYOUT_DIRECTION_RESOLVED_RTL
#define android_webkit_WebView_PFLAG2_LAYOUT_DIRECTION_RESOLVED_RTL 16L
#undef android_webkit_WebView_PFLAG2_LAYOUT_DIRECTION_RESOLVED
#define android_webkit_WebView_PFLAG2_LAYOUT_DIRECTION_RESOLVED 32L
#undef android_webkit_WebView_PFLAG2_LAYOUT_DIRECTION_RESOLVED_MASK
#define android_webkit_WebView_PFLAG2_LAYOUT_DIRECTION_RESOLVED_MASK 48L
#undef android_webkit_WebView_SCROLL_AXIS_NONE
#define android_webkit_WebView_SCROLL_AXIS_NONE 0L
#undef android_webkit_WebView_SCROLL_AXIS_HORIZONTAL
#define android_webkit_WebView_SCROLL_AXIS_HORIZONTAL 1L
#undef android_webkit_WebView_SCROLL_AXIS_VERTICAL
#define android_webkit_WebView_SCROLL_AXIS_VERTICAL 2L
#undef android_webkit_WebView_OVER_SCROLL_ALWAYS
#define android_webkit_WebView_OVER_SCROLL_ALWAYS 0L
#undef android_webkit_WebView_OVER_SCROLL_IF_CONTENT_SCROLLS
#define android_webkit_WebView_OVER_SCROLL_IF_CONTENT_SCROLLS 1L
#undef android_webkit_WebView_OVER_SCROLL_NEVER
#define android_webkit_WebView_OVER_SCROLL_NEVER 2L
#undef android_webkit_WebView_STATUS_BAR_HIDDEN
#define android_webkit_WebView_STATUS_BAR_HIDDEN 1L
#undef android_webkit_WebView_STATUS_BAR_VISIBLE
#define android_webkit_WebView_STATUS_BAR_VISIBLE 0L
#undef android_webkit_WebView_SYSTEM_UI_FLAG_FULLSCREEN
#define android_webkit_WebView_SYSTEM_UI_FLAG_FULLSCREEN 4L
#undef android_webkit_WebView_SYSTEM_UI_FLAG_HIDE_NAVIGATION
#define android_webkit_WebView_SYSTEM_UI_FLAG_HIDE_NAVIGATION 2L
#undef android_webkit_WebView_SYSTEM_UI_FLAG_IMMERSIVE
#define android_webkit_WebView_SYSTEM_UI_FLAG_IMMERSIVE 2048L
#undef android_webkit_WebView_SYSTEM_UI_FLAG_IMMERSIVE_STICKY
#define android_webkit_WebView_SYSTEM_UI_FLAG_IMMERSIVE_STICKY 4096L
#undef android_webkit_WebView_SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
#define android_webkit_WebView_SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN 1024L
#undef android_webkit_WebView_SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
#define android_webkit_WebView_SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION 512L
#undef android_webkit_WebView_SYSTEM_UI_FLAG_LAYOUT_STABLE
#define android_webkit_WebView_SYSTEM_UI_FLAG_LAYOUT_STABLE 256L
#undef android_webkit_WebView_SYSTEM_UI_FLAG_LOW_PROFILE
#define android_webkit_WebView_SYSTEM_UI_FLAG_LOW_PROFILE 1L
#undef android_webkit_WebView_SYSTEM_UI_FLAG_VISIBLE
#define android_webkit_WebView_SYSTEM_UI_FLAG_VISIBLE 0L
#undef android_webkit_WebView_SYSTEM_UI_LAYOUT_FLAGS
#define android_webkit_WebView_SYSTEM_UI_LAYOUT_FLAGS 1536L
#undef android_webkit_WebView_TEXT_ALIGNMENT_CENTER
#define android_webkit_WebView_TEXT_ALIGNMENT_CENTER 4L
#undef android_webkit_WebView_TEXT_ALIGNMENT_GRAVITY
#define android_webkit_WebView_TEXT_ALIGNMENT_GRAVITY 1L
#undef android_webkit_WebView_TEXT_ALIGNMENT_INHERIT
#define android_webkit_WebView_TEXT_ALIGNMENT_INHERIT 0L
#undef android_webkit_WebView_TEXT_ALIGNMENT_TEXT_END
#define android_webkit_WebView_TEXT_ALIGNMENT_TEXT_END 3L
#undef android_webkit_WebView_TEXT_ALIGNMENT_TEXT_START
#define android_webkit_WebView_TEXT_ALIGNMENT_TEXT_START 2L
#undef android_webkit_WebView_TEXT_ALIGNMENT_VIEW_END
#define android_webkit_WebView_TEXT_ALIGNMENT_VIEW_END 6L
#undef android_webkit_WebView_TEXT_ALIGNMENT_VIEW_START
#define android_webkit_WebView_TEXT_ALIGNMENT_VIEW_START 5L
#undef android_webkit_WebView_TEXT_DIRECTION_ANY_RTL
#define android_webkit_WebView_TEXT_DIRECTION_ANY_RTL 2L
#undef android_webkit_WebView_TEXT_DIRECTION_FIRST_STRONG
#define android_webkit_WebView_TEXT_DIRECTION_FIRST_STRONG 1L
#undef android_webkit_WebView_TEXT_DIRECTION_INHERIT
#define android_webkit_WebView_TEXT_DIRECTION_INHERIT 0L
#undef android_webkit_WebView_TEXT_DIRECTION_LOCALE
#define android_webkit_WebView_TEXT_DIRECTION_LOCALE 5L
#undef android_webkit_WebView_TEXT_DIRECTION_LTR
#define android_webkit_WebView_TEXT_DIRECTION_LTR 3L
#undef android_webkit_WebView_TEXT_DIRECTION_RTL
#define android_webkit_WebView_TEXT_DIRECTION_RTL 4L
#undef android_webkit_WebView_FLAG_CLIP_CHILDREN
#define android_webkit_WebView_FLAG_CLIP_CHILDREN 1L
#undef android_webkit_WebView_FLAG_INVALIDATE_REQUIRED
#define android_webkit_WebView_FLAG_INVALIDATE_REQUIRED 4L
#undef android_webkit_WebView_FLAG_ANIMATION_DONE
#define android_webkit_WebView_FLAG_ANIMATION_DONE 16L
#undef android_webkit_WebView_FLAG_OPTIMIZE_INVALIDATE
#define android_webkit_WebView_FLAG_OPTIMIZE_INVALIDATE 128L
#undef android_webkit_WebView_FLAG_CLEAR_TRANSFORMATION
#define android_webkit_WebView_FLAG_CLEAR_TRANSFORMATION 256L
#undef android_webkit_WebView_FLAG_USE_CHILD_DRAWING_ORDER
#define android_webkit_WebView_FLAG_USE_CHILD_DRAWING_ORDER 1024L
#undef android_webkit_WebView_FLAG_SUPPORT_STATIC_TRANSFORMATIONS
#define android_webkit_WebView_FLAG_SUPPORT_STATIC_TRANSFORMATIONS 2048L
#undef android_webkit_WebView_FLAG_MASK_FOCUSABILITY
#define android_webkit_WebView_FLAG_MASK_FOCUSABILITY 393216L
#undef android_webkit_WebView_FOCUS_BEFORE_DESCENDANTS
#define android_webkit_WebView_FOCUS_BEFORE_DESCENDANTS 131072L
#undef android_webkit_WebView_FOCUS_AFTER_DESCENDANTS
#define android_webkit_WebView_FOCUS_AFTER_DESCENDANTS 262144L
#undef android_webkit_WebView_FOCUS_BLOCK_DESCENDANTS
#define android_webkit_WebView_FOCUS_BLOCK_DESCENDANTS 393216L
#undef android_webkit_WebView_FLAG_DISALLOW_INTERCEPT
#define android_webkit_WebView_FLAG_DISALLOW_INTERCEPT 524288L
#undef android_webkit_WebView_FLAG_IS_TRANSITION_GROUP
#define android_webkit_WebView_FLAG_IS_TRANSITION_GROUP 16777216L
#undef android_webkit_WebView_FLAG_IS_TRANSITION_GROUP_SET
#define android_webkit_WebView_FLAG_IS_TRANSITION_GROUP_SET 33554432L
#undef android_webkit_WebView_FLAG_TOUCHSCREEN_BLOCKS_FOCUS
#define android_webkit_WebView_FLAG_TOUCHSCREEN_BLOCKS_FOCUS 67108864L
/*
 * Class:     android_webkit_WebView
 * Method:    native_constructor
 * Signature: (Landroid/content/Context;Landroid/util/AttributeSet;)J
 */
JNIEXPORT jlong JNICALL Java_android_webkit_WebView_native_1constructor
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     android_webkit_WebView
 * Method:    native_loadDataWithBaseURL
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_webkit_WebView_native_1loadDataWithBaseURL
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring);

/*
 * Class:     android_webkit_WebView
 * Method:    native_loadUrl
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_webkit_WebView_native_1loadUrl
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     android_webkit_WebView
 * Method:    native_getUrl
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_webkit_WebView_native_1getUrl
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_webkit_WebView
 * Method:    native_canGoBack
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_android_webkit_WebView_native_1canGoBack
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_webkit_WebView
 * Method:    native_goBack
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_webkit_WebView_native_1goBack
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_webkit_WebView
 * Method:    native_setJavaScriptEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_android_webkit_WebView_native_1setJavaScriptEnabled
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     android_webkit_WebView
 * Method:    native_setDomStorageEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_android_webkit_WebView_native_1setDomStorageEnabled
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     android_webkit_WebView
 * Method:    native_setMediaPlaybackRequiresUserGesture
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_android_webkit_WebView_native_1setMediaPlaybackRequiresUserGesture
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     android_webkit_WebView
 * Method:    native_evaluateJavascript
 * Signature: (JLjava/lang/String;Landroid/webkit/ValueCallback;)V
 */
JNIEXPORT void JNICALL Java_android_webkit_WebView_native_1evaluateJavascript
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     android_webkit_WebView
 * Method:    native_permissionAllow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_webkit_WebView_native_1permissionAllow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_webkit_WebView
 * Method:    native_permissionDeny
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_webkit_WebView_native_1permissionDeny
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_webkit_WebView
 * Method:    native_fileChooserSelect
 * Signature: (J[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_webkit_WebView_native_1fileChooserSelect
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     android_webkit_WebView
 * Method:    native_fileChooserCancel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_webkit_WebView_native_1fileChooserCancel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_webkit_WebView
 * Method:    native_fileChooserOpenGtk
 * Signature: (JZLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_webkit_WebView_native_1fileChooserOpenGtk
  (JNIEnv *, jclass, jlong, jboolean, jstring);

#ifdef __cplusplus
}
#endif
#endif
